package security

import "strings"

var badUserAgentStrings = []string{
	"01h4x.com",
	"360spider",
	"404checker",
	"404enemy",
	"80legs",
	"abonti",
	"aboundex",
	"aboundexbot",
	"acunetix",
	"admantx",
	"adscanner",
	"afd-verbotsverfahren",
	"ahrefsbot",
	"aibot",
	"aihitbot",
	"aipbot",
	"alexibot",
	"alittle client",
	"alligator",
	"allsubmitter",
	"alphabot",
	"anarchie",
	"anarchy",
	"anarchy99",
	"ankit",
	"anthill",
	"apexoo",
	"archive.org_bot",
	"arquivo.pt",
	"arquivo-web-crawler",
	"aspiegel",
	"aspseek",
	"asterias",
	"atomseobot",
	"attach",
	"autoemailspider",
	"awariorssbot",
	"awariosmartbot",
	"backdoorbot",
	"backlink-ceck",
	"backlink-check",
	"backlinkcrawler",
	"backstreet",
	"backweb",
	"badass",
	"bandit",
	"barkrowler",
	"batchftp",
	"battleztar bazinga",
	"bbbike",
	"bdcbot",
	"bdfetch",
	"betabot",
	"bigfoot",
	"bitacle",
	"blackboard",
	"black hole",
	"blackwidow",
	"blexbot",
	"blow",
	"blowfish",
	"boardreader",
	"bolt",
	"bordermanager",
	"botalot",
	"brandprotect",
	"brandwatch",
	"buck",
	"buddy",
	"builtbottough",
	"builtwith",
	"bullseye",
	"bunnyslippers",
	"burpcollaborator",
	"buzzsumo",
	"cah.io.community",
	"calculon",
	"catexplorador",
	"cazoodlebot",
	"ccbot",
	"cegbfeieh",
	"censysinspect",
	"check1.exe",
	"cheesebot",
	"cherrypicker",
	"cheteam",
	"chinaclaw",
	"chlooe",
	"citoid",
	"clamav",
	"claritybot",
	"clark-crawler",
	"cliqzbot",
	"cloud mapping",
	"coccocbot",
	"cocolyzebot",
	"code87",
	"cogentbot",
	"cognitiveseo",
	"collector",
	"com.plumanalytics",
	"copier",
	"copyrightcheck",
	"copyscape",
	"cosmos",
	"craftbot",
	"crawler4j",
	"crawler.feedback",
	"crawling at home project",
	"crawl.sogou.com",
	"crazywebcrawler",
	"crescent",
	"crunchbot",
	"cshttp",
	"curious",
	"custo",
	"cyotekwebcopy",
	"databasedrivermysqli",
	"datacha0s",
	"dataforseo.com",
	"dblbot",
	"demandbase-bot",
	"demon",
	"deusu",
	"devil",
	"digincore",
	"digitalpebble",
	"diibot",
	"dirbuster",
	"disco",
	"discobot",
	"discoverybot",
	"dispatch",
	"dittospyder",
	"dnbcrawler-analytics",
	"dnyzbot",
	"domainappender",
	"domaincrawler",
	"domainsigmacrawler",
	"domains project",
	"domainsproject.org",
	"domainstatsbot",
	"domcopbot",
	"dotbot",
	"download wonder",
	"dragonfly",
	"drip",
	"dsearch",
	"dts agent",
	"easydl",
	"ebingbong",
	"ecatch",
	"eccp/1.0",
	"ecxi",
	"eirgrabber",
	"email siphon",
	"email wolf",
	"erocrawler",
	"evc-batch",
	"evil",
	"exabot",
	"express webpictures",
	"extlinksbot",
	"extractor",
	"extractorpro",
	"extreme picture finder",
	"eyenetie",
	"ezooms",
	"facebookscraper",
	"fdm",
	"femtosearchbot",
	"fhscan",
	"fimap",
	"firefox/7.0",
	"flashget",
	"flunky",
	"foobot",
	"freeuploader",
	"frontpage",
	"fuzz",
	"fyberspider",
	"fyrebot",
	"galaxybot",
	"genieo",
	"germcrawler",
	"getintent",
	"getright",
	"getweb",
	"g-i-g-a-b-o-t",
	"gigabot",
	"go-ahead-got-it",
	"gopher",
	"gotit",
	"go!zilla",
	"gozilla",
	"grabber",
	"grabnet",
	"grafula",
	"grapefx",
	"grapeshotcrawler",
	"gridbot",
	"gt::www",
	"haansoft",
	"haosouspider",
	"harvest",
	"havij",
	"headmasterseo",
	"heritrix",
	"heritrix",
	"hloader",
	"hmview",
	"honolulubot",
	"htmlparser",
	"http::lite",
	"httrack",
	"humanlinks",
	"hybridbot",
	"iblog",
	"idbot",
	"idbte4m",
	"id-search",
	"ilsebot",
	"image fetch",
	"image sucker",
	"indeedbot",
	"indy library",
	"infonavirobot",
	"infotekies",
	"instabid",
	"intelliseek",
	"interget",
	"internet ninja",
	"internetseer",
	"internetvista monitor",
	"ips-agent",
	"iria",
	"irlbot",
	"isitwp.com",
	"iskanie",
	"istellabot",
	"iubenda-radar",
	"jamesbot",
	"jbrofuzz",
	"jennybot",
	"jetcar",
	"jetty",
	"jikespider",
	"joc web spider",
	"joomla",
	"jorgee",
	"justview",
	"jyxobot",
	"kenjin spider",
	"keybot translation-search-machine",
	"keyword density",
	"kinza",
	"kozmosbot",
	"lanshanbot",
	"larbin",
	"leap",
	"leechftp",
	"leechget",
	"lexibot",
	"lftp",
	"libweb",
	"libwhisker",
	"liebaofast",
	"lightspeedsystems",
	"likse",
	"linkbot",
	"linkdexbot",
	"linkextractorpro",
	"linkpadbot",
	"linkscan",
	"linksmanager",
	"linkwalker",
	"linqiametadatadownloaderbot",
	"linqiarssbot",
	"linqiascrapebot",
	"lipperhey",
	"lipperhey spider",
	"litemage_walker",
	"lmspider",
	"lnspiderguy",
	"ltx71",
	"lwp-request",
	"lwp::simple",
	"lwp-trivial",
	"magnet",
	"mag-net",
	"magpie-crawler",
	"mail.ru_bot",
	"majestic12",
	"majestic-seo",
	"majestic seo",
	"markmonitor",
	"markwatch",
	"masscan",
	"mass downloader",
	"mata hari",
	"mauibot",
	"mb2345browser",
	"meanpathbot",
	"meanpathbot",
	"meanpath bot",
	"mediatoolkitbot",
	"mediawords",
	"megaindex.ru",
	"metauri",
	"mfc_tear_sample",
	"micromessenger",
	"microsoft data access",
	"microsoft url control",
	"midown tool",
	"miixpc",
	"minefield",
	"mister pix",
	"mj12bot",
	"moblie safari",
	"mojeek",
	"mojolicious",
	"molokaibot",
	"morfeus fucking scanner",
	"mozlila",
	"mqqbrowser",
	"mr.4x3",
	"msfrontpage",
	"msiecrawler",
	"msrabot",
	"mtrobot",
	"muhstik-scan",
	"musobot",
	"name intelligence",
	"nameprotect",
	"navroad",
	"nearsite",
	"needle",
	"nessus",
	"netants",
	"netcraft",
	"netestate ne crawler",
	"netlyzer",
	"netmechanic",
	"netspider",
	"nettrack",
	"net vampire",
	"netvibes",
	"netzip",
	"nextgensearchbot",
	"nibbler",
	"nicerspro",
	"niki-bot",
	"nikto",
	"nimblecrawler",
	"nimbostratus",
	"ninja",
	"nmap",
	"not",
	"npbot",
	"nuclei",
	"nutch",
	"obot",
	"octopus",
	"offline explorer",
	"offline navigator",
	"oncrawl",
	"openfind",
	"openlinkprofiler",
	"openvas",
	"openvas",
	"orangebot",
	"orangespider",
	"outclicksbot",
	"outfoxbot",
	"page analyzer",
	"pageanalyzer",
	"pagegrabber",
	"page scorer",
	"pagescorer",
	"pagething.com",
	"pandalytics",
	"panscient",
	"papa foto",
	"pavuk",
	"pcbrowser",
	"pecl::http",
	"peoplepal",
	"petalbot",
	"phpcrawl",
	"picscout",
	"picsearch",
	"picturefinder",
	"piepmatz",
	"pimonster",
	"pi-monster",
	"pixray",
	"pleasecrawl",
	"plumanalytics",
	"pockey",
	"poe-component-client-http",
	"polaris version",
	"probe-image-size",
	"probethenet",
	"propowerbot",
	"prowebwalker",
	"psbot",
	"pu_in",
	"pump",
	"pxbroker",
	"pycurl",
	"queryn metasearch",
	"quick-crawler",
	"rankactive",
	"rankactivelinkbot",
	"rankflex",
	"rankingbot",
	"rankingbot2",
	"rankivabot",
	"rankurbot",
	"realdownload",
	"reaper",
	"rebelmouse",
	"recorder",
	"redesscrapy",
	"reget",
	"repomonkey",
	"re-re",
	"ripper",
	"ripz",
	"rocketcrawler",
	"rogerbot",
	"rssingbot",
	"s1z.ru",
	"salesintelligent",
	"satoristudio.net",
	"sbider",
	"scalaj-http",
	"scanalert",
	"scanbot",
	"scan.lol",
	"scoutjet",
	"scrapy",
	"screaming",
	"screenerbot",
	"screpybot",
	"searchestate",
	"searchmetricsbot",
	"seekport",
	"semanticjuice",
	"semrush",
	"semrushbot",
	"sentibot",
	"seobility",
	"seobilitybot",
	"seocompany.store",
	"seokicks",
	"seokicks-robot",
	"seolyticscrawler",
	"seomoz",
	"seoprofiler",
	"seoscanners",
	"seositecheckup",
	"seostar",
	"seostats",
	"serpstatbot",
	"sexsearcher",
	"shodan",
	"siphon",
	"sistrix",
	"sitebeam",
	"sitecheckerbotcrawler",
	"sitechecker.pro",
	"siteexplorer",
	"siteimprove",
	"sitelockspider",
	"siteripz",
	"sitesnagger",
	"site sucker",
	"sitesucker",
	"sitevigil",
	"slysearch",
	"smartdownload",
	"smtbot",
	"snake",
	"snapbot",
	"snoopy",
	"socialrankiobot",
	"sociscraper",
	"sogouspider",
	"sogou web spider",
	"sosospider",
	"sottopop",
	"spacebison",
	"spammen",
	"spankbot",
	"spanner",
	"sp_auditbot",
	"spbot",
	"spinn3r",
	"sputnikbot",
	"spyfu",
	"sqlmap",
	"sqlworm",
	"sqworm",
	"steeler",
	"stripper",
	"ssl labs",
	"sucker",
	"sucuri",
	"superbot",
	"superhttp",
	"surfbot",
	"surveybot",
	"suzuran",
	"swiftbot",
	"sysscan",
	"szukacz",
	"t0phackteam",
	"t8abot",
	"takeout",
	"teleport",
	"teleportpro",
	"telesoft",
	"telesphoreo",
	"telesphorep",
	"the intraformant",
	"thenomad",
	"thumbor",
	"tighttwatbot",
	"titan",
	"toata",
	"toweyabot",
	"tracemyfile",
	"trendiction",
	"trendictionbot",
	"trendiction.com",
	"trendiction.de",
	"true_robot",
	"turingos",
	"turnitin",
	"turnitinbot",
	"twengabot",
	"twice",
	"typhoeus",
	"ubermetrics-technologies.com",
	"unisterbot",
	"upflow",
	"urly.warning",
	"urly warning",
	"vacuum",
	"vagabondo",
	"v-bot",
	"vb project",
	"vci",
	"velenpublicwebcrawler",
	"vericitecrawler",
	"vidiblescraper",
	"virusdie",
	"voideye",
	"voil",
	"voltron",
	"voyagerx.com",
	"wallpapers",
	"wallpapers/3.0",
	"wallpapershd",
	"wasalive-bot",
	"wbsearchbot",
	"webalta",
	"web auto",
	"webauto",
	"webbandit",
	"web collage",
	"webcollage",
	"webcopier",
	"webdav",
	"web enhancer",
	"webenhancer",
	"web fetch",
	"webfetch",
	"web fuck",
	"webfuck",
	"webgains-bot",
	"webgo is",
	"webimagecollector",
	"webleacher",
	"webmasterworldforumbot",
	"webmeup-crawler",
	"web pix",
	"webpix",
	"webprosbot",
	"webpros.com",
	"webreaper",
	"web sauger",
	"websauger",
	"webshag",
	"websiteextractor",
	"website quester",
	"websitequester",
	"webster",
	"webstripper",
	"web sucker",
	"websucker",
	"webwhacker",
	"webzip",
	"wesee",
	"whack",
	"whacker",
	"whatweb",
	"who.is bot",
	"widow",
	"winhttrack",
	"wiseguys robot",
	"wisenutbot",
	"wonderbot",
	"woobot",
	"wotbox",
	"wprecon",
	"wpscan",
	"www-collector-e",
	"www-mechanize",
	"www::mechanize",
	"wwwoffle",
	"x09mozilla",
	"x22mozilla",
	"xaldon webspider",
	"xaldon_webspider",
	"xenu",
	"xpymep1.exe",
	"youdaobot",
	"zade",
	"zauba",
	"zauba.io",
	"zermelo",
	"zeus",
	"zgrab",
	"zitebot",
	"zmeu",
	"zoombot",
	"zoominfobot",
	"zumbot",
	"zyborg",
}

func IsUserAgentBad(u string, allowBlank bool) bool {

	//  a user agent SHOULD be sent: https://www.rfc-editor.org/rfc/rfc7231#section-5.5.3
	if allowBlank == false && u == "" {
		return true
	}

	u = strings.ToLower(u)

	for _, badString := range badUserAgentStrings {
		if strings.Contains(u, badString) {
			return true
		}
	}
	return false
}
