services:
  dnd_mysql_test:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: dnd_db_test
    env_file:
      - .env
    ports:
      - ${TEST_EXPOSE_DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_ROOT_HOST=${DB_HOST}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - database_mysql_test:/var/lib/mysql

volumes:
  database_mysql_test: