package seeders

import (
	"dnd-api/db/models"
	"log"
)

func (s *Seeder) SetCharacters() {
	characters := []models.Character{
		{
			ID:                     1,
			Name:                   "Faelan Haversham",
			ProfilePictureURL:      "https://www.dndbeyond.com/avatars/40171/941/1581111423-117906084.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp",
			Level:                  3,
			ClassID:                3,
			RaceID:                 18,
			Strength:               12,
			Dexterity:              16,
			Constitution:           14,
			Intelligence:           10,
			Wisdom:                 15,
			Charisma:               8,
			CurrentHitPoints:       28,
			MaxHitPoints:           28,
			ProficientDexterity:    true,
			ProficientIntelligence: true,
			BackgroundName:         "Outlander",
			Alignment:              "Lawful Good",
			Gender:                 "Male",
			Eyes:                   "Green",
			Size:                   "Small",
			Height:                 `3' 2"`,
			Hair:                   "Tousled Brown",
			Skin:                   "White",
			Age:                    27,
			Weight:                 45,
			AttacksPerAction:       1,
			Allies:                 `Erenis Hydref, Mayleaf, Perra Turnuroth, Thaddius "Thaddy" Aethelbald`,
			Backstory:              "Faelan Haversham, a Stout Halfling of Acosis, was born into a family deeply rooted in the lumber and food trade that sustained their isolated community. The Havershams were known for their resilience and resourcefulness in the face of the harsh conditions surrounding Acosis, relying on a careful balance of agriculture and forestry to meet the needs of their people. Faelan's father, Thorian Haversham, was a skilled woodsman who oversaw the logging operations, while his mother, Elowen Haversham, managed the agricultural aspects, ensuring the community had enough sustenance.\n\nGrowing up in the shadow of the constant threat of Arreksis raids, Faelan developed a strong sense of duty towards the safety and prosperity of Acosis. He learned the art of survival in the depths of the forests where trade access was impossible. Faelan's childhood was marked by stories of the Mortonhelm disaster, a cautionary tale shared by elders to emphasise the dangers of unchecked magical forces.\n\nOne day, as Faelan explored the dense forests of Acosis, he stumbled upon a hidden glade where an ancient and mystical gem lay nestled among the roots of an ancient tree. The gem radiated a peculiar energy that captivated Faelan's senses. Intrigued and fueled by a desire to understand the gem's origins and purpose, he embarked on a journey beyond the borders of Acosis. \n\nMaking his way to Myrinport, the bustling trade hub of Fortenua, Faelan sought out scholars and mages who could shed light on the mysterious gem. He was instructed to head to the famed Crenchai Isle, known for its strong magical presence and abundance of temples. He was assured that the priests and scholars of the Isle could answer his questions. \n\nHe was set to head out from Myrinport dock and travel by boat to Crenchai Isle that evening. However, fate had other plans for him. As he navigated the crowded streets of Myrinport, the city's alarm bells suddenly pierced the air, and a frantic voice called out, \"All to the square! All to the square!\" With a mix of curiosity and concern, Faelan joined the gathering crowd, his hand resting on the gem he kept close. \n\nIn the midst of the commotion, a mysterious figure touched Faelan's shoulder. Before he could react, a surge of energy coursed through him, and the world blurred as he lost consciousness…\n",
		},
		{
			ID:                     2,
			Name:                   "PeeWee McAnkle-Biter",
			Level:                  5,
			ProfilePictureURL:      "https://www.dndbeyond.com/avatars/17/969/636378926856690034.png?width=150&height=150&fit=crop&quality=95&auto=webp",
			ClassID:                1,
			RaceID:                 3,
			Strength:               16,
			Dexterity:              14,
			Constitution:           16,
			Intelligence:           12,
			Wisdom:                 11,
			Charisma:               8,
			WalkingSpeedModifier:   10,
			CurrentHitPoints:       49,
			MaxHitPoints:           60,
			ProficientStrength:     true,
			ProficientConstitution: true,
			InitiativeModifier:     5,
			AttacksPerAction:       2,
			BackgroundName:         "Soldier",
			Alignment:              "Chaotic Good",
			Gender:                 "Male",
			Eyes:                   "Blue",
			Size:                   "Medium",
			Height:                 `5' 2"`,
			Hair:                   "Dark Ginger",
			Skin:                   "White",
			Age:                    193,
			Weight:                 190,
		},
		{
			ID:                     3,
			Name:                   "Iratham Veomakute",
			Level:                  3,
			ClassID:                3,
			RaceID:                 14,
			ProfilePictureURL:      "https://www.dndbeyond.com/avatars/36645/678/1581111423-94761552.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp",
			Strength:               18,
			Dexterity:              13,
			Constitution:           14,
			Intelligence:           15,
			Wisdom:                 11,
			Charisma:               11,
			CurrentHitPoints:       34,
			MaxHitPoints:           34,
			ProficientDexterity:    true,
			ProficientIntelligence: true,
			AttacksPerAction:       1,
			BackgroundName:         "Outlander",
			Alignment:              "Chaotic Neutral",
			Gender:                 "Male",
			Eyes:                   "Dark and Bloodshot",
			Size:                   "Large",
			Height:                 `8' 2"`,
			Hair:                   "Bald",
			Skin:                   "Pale grey with tribal markings and scars",
			Age:                    32,
			Weight:                 280,
			Allies:                 "Sylla Cameron, Idris, Gooby Goobus, Abcde Orianna, Octavius the God Butcher, Kaori",
			Backstory:              "Iratham Veomakute, known as Ira, began his life as the eldest son of Keodak and Lilane, leaders of a formidable goliath tribe known as The Cull that inhabited the Frostback Mountains. From a young age, it was evident that Ira was destined for leadership, following in his father's footsteps. However, before he could assume this weighty responsibility, he faced a final, fateful test that would forever alter the course of his life.\n\nThis pivotal challenge unfolded deep within a nearby forest, where whispers of a colossal and enigmatic beast had reached the tribe's ears through vigilant scouts. Ira, accompanied by his spirited younger brother Madath and a select group of the tribe's most formidable warriors, embarked on an arduous journey into the heart of the wilderness to track down this elusive creature. Days turned into nights as they doggedly pursued its trail, but their tireless efforts yielded naught but frustration.\n\nOn the eve of their planned return to the tribe, tragedy struck with devastating force. The elusive beast, cunning and relentless, launched a ferocious attack upon their camp while they lay in slumber, shattering their dreams and extinguishing their lives. Ira alone survived the brutal onslaught, though he bore grievous injuries that would forever mark his body.\n\nUpon his return to the tribe, Ira's father reacted with a tumultuous mixture of grief and anger. He couldn't forgive Ira for the loss of Madath, who had always held a special place in his heart. The weight of his father's wrath and the tribe's disappointment crushed Ira's spirit, propelling him towards isolation in the aftermath of the tragedy.\n\nAs the seasons waxed and waned, Ira sensed an inexplicable transformation deep within himself. The injuries inflicted by the beast had bestowed upon him newfound and enigmatic magical abilities. Driven by an insatiable curiosity inherited from his mother, he began to experiment, drawing upon the very essence of his life force to harness these powers.\n\nHis father, discovering Ira's unorthodox pursuits, erupted in outrage and forcibly removed his son from their home, exiling him from the tribe's close-knit embrace. Lilane, Ira's mother, protested vehemently, but her pleas fell upon deaf ears as his father remained resolute in his decision.\n\nAnd so, Ira embarked on a solitary odyssey that spanned over a decade, wandering the land and relying on sporadic mercenary work to eke out a meager existence. He became a master of solitude, rarely engaging in conversation with others and preferring the company of his own thoughts.\n\nIt was during this time that fate guided him to a merchant ship bound for an archipelago far to the south, landing him in the bustling port city of Yraso. Little did he know that this voyage would lead him to a city teeming with opportunities and rumors of a wealthy benefactor seeking skilled fighters to aid in an impending conflict. With a heart steeled by years of isolation and a newfound sense of purpose, Ira set his sights on Klouset, determined to seek out this mysterious patron and embrace the chance for redemption and a new path in life.",
		},
		{
			ID:                     4,
			Name:                   "Kael Drakeshield",
			Level:                  4,
			ClassID:                6,
			RaceID:                 2,
			ProfilePictureURL:      "https://www.dndbeyond.com/avatars/42817/335/1581111423-124892113.jpeg?width=150&height=150&fit=crop&quality=95&auto=webp",
			Strength:               19,
			Dexterity:              15,
			Constitution:           19,
			Intelligence:           6,
			Wisdom:                 14,
			Charisma:               11,
			Inspiration:            true,
			CurrentHitPoints:       43,
			MaxHitPoints:           43,
			ProficientStrength:     true,
			ProficientConstitution: true,
			AttacksPerAction:       1,
			BackgroundName:         "Urban Bounty Hunter",
			Alignment:              "Lawful Good",
			Gender:                 "Male",
			Eyes:                   "Amber",
			Size:                   "Medium",
			Height:                 `6' 6"`,
			Hair:                   "A crown of curved horns",
			Skin:                   "Brass/Gold-Brown",
			Age:                    22,
			Weight:                 270,
			Organisations:          "Inter-Isle Belonging of Fantastical Investigators (IIBFI) - Marblethorn Unit",
			Allies:                 "Idris, Lycia, Nikoline Nightstriker, Vashta",
			Backstory:              "Kaelrith Drakeshield was born in the harsh, arid lands of the Draken Wastes, a barren region where only the strongest survived. From a young age, he was taught to fend for himself, honing his skills as a warrior under the tutelage of his clan's elders. The Draken Wastes were a lawless land, and Kael quickly learned the ways of combat, developing into a skilled bounty hunter by his late teens. His physical prowess and brass dragonborn resilience made him a feared and respected figure among the bounty hunting community.\n\nHowever, life as a bounty hunter was not without its complications. Kael's straightforward nature often got him into trouble, and he made more enemies than friends along the way. One such enemy was a notorious crime lord, Garvin the Ruthless, whom Kael had crossed during a high-stakes job. The confrontation left Kael with a considerable debt, as Garvin demanded retribution for the loss of his men and resources. Desperate and with few options, Kael found an unexpected benefactor in an eccentric wizard named Eldrin Valtoris.\n\nEldrin saw potential in the young dragonborn and offered to pay off his debt in exchange for Kael's service and loyalty. Kael accepted, grateful for the wizard's generosity. Under Eldrin's guidance, Kael was introduced to the arcane arts, specifically the Echo Knight discipline. This allowed Kael to summon spectral echoes of himself in battle, an ability that greatly enhanced his combat effectiveness.\n\nAfter several years of service, Eldrin released Kael from his obligation, though Kael felt indebted to the wizard and vowed to repay him fully one day. Seeking a new purpose, Kael joined the Marblethorn Unit of the Inter-Isle Belonging of Fantastic Investigators (IIBFI) two years ago. The unit, known for tackling supernatural threats and complex investigations across the Isles, provided Kael with a new avenue to use his skills for a greater good.\n\nThough his intellect often lags behind his peers, Kael's unwavering determination and combat expertise have earned him a place of respect within the Marblethorn Unit. He continues to work tirelessly, hoping to one day repay Eldrin and honor the legacy of his clan. Kael's journey is one of redemption and loyalty, as he seeks to balance the scales of his past while forging a future as a protector and defender.",
		},
	}

	for _, character := range characters {
		err := s.DB.Where("id = ?", character.ID).FirstOrCreate(&character).Error
		if err != nil {
			log.Printf("error creating character %s: %s", character.Name, err.Error())
		}
	}
}
