package seeders

import (
	m "dnd-api/db/models"
	"log"
)

func (s *Seeder) SetClassFeatures() {
	classFeatures := []*m.ClassFeature{
		{
			ID:       "bard-core-bard-traits",
			ClassId:  1,
			Level:    1,
			Name:     "Core Bard Traits",
			Priority: 1,
		},
		{
			ID:      "bard-bardic-inspiration",
			ClassId: 1,
			Level:   1,
			Name:    "Bard Inspiration",
			Description: `As a Bonus Action, you can inspire another creature within 60 ft. that can see or hear you. That creatures gains one of your bardic inspiration dice (1d6, [5th] 1d8, [10th] 1d10, [15th] 1d12). Once within the next hour, when the creature fails a d20 Test, the creature can roll the Bardic Inspiration die and add the number rolled to the total, potentially turning the failure into a success.

You can confer your Bardic Inspiration die a number of times equal to your Charisma Modifier per Long Rest`,
			Priority: 2,
		},
		{
			ID:          "bard-spellcasting",
			ClassId:     1,
			Level:       1,
			Name:        "Spellcasting",
			Description: "You can cast spells through your bardic arts. Charisma is your spellcasting ability for your Bard Spells. You can use a Musical Instrument as a Spellcasting Focus for your Bard Spells.",
			Priority:    3,
		},
		{
			ID:          "bard-expertise-2",
			ClassId:     1,
			Level:       2,
			Name:        "Expertise",
			Description: "You gain Expertise in two skill proficiencies of your choice.",
			Priority:    4,
		},
		{
			ID:          "bard-jack-of-all-trades",
			ClassId:     1,
			Level:       2,
			Name:        "Jack of All Trades",
			Description: "You can add half your Proficiency Bonus to ability checks you make that uses a skill proficiency you lack and that doesn't otherwise use your Proficiency Bonus.",
			Priority:    5,
		},
		{
			ID:       "bard-subclass",
			ClassId:  1,
			Level:    3,
			Name:     "Bard Subclass",
			Priority: 6,
		},
		{
			ID:       "bard-asi-4",
			ClassId:  1,
			Level:    4,
			Name:     "Ability Score Improvement",
			Priority: 7,
		},
		{
			ID:      "bard-font-of-inspiration",
			ClassId: 1,
			Level:   5,
			Name:    "Font of Inspiration",
			Description: `You now regain all expended uses of Bardic Inspiration when you finish a Short or Long rest.

In addition, you can expend a spell slot (no action required) to regain one expended use of Bardic Inspiration`,
			Priority: 8,
		},
		{
			ID:          "bard-countercharm",
			ClassId:     1,
			Level:       6,
			Name:        "Countercharm",
			Description: "If you or a creature within 30ft. fails a saving throw against an effect that applies the Charmed or Frightened condition, you can take a Reaction to cause the save to be rerolled with Advantage.",
			Priority:    9,
		},
		{
			ID:       "bard-asi-8",
			ClassId:  1,
			Level:    8,
			Name:     "Ability Score Improvement",
			Priority: 10,
		},
		{
			ID:          "bard-expertise-9",
			ClassId:     1,
			Level:       9,
			Name:        "Expertise",
			Description: "You gain Expertise in another two skill proficiencies of your choice.",
			Priority:    11,
		},
		{
			ID:          "bard-magical-secrets",
			ClassId:     1,
			Level:       10,
			Name:        "Magical Secrets",
			Description: "Whenever you reach a Bard level that increases the number of Prepared Spells you have, you can choose any of your new prepared spells from the Bard, Cleric, Druid, and Wizard spell lists, and they count as Bard spells for you. In addition, whenever you replace a spell prepared for this class, you can replace it with a spell from those lists.",
			Priority:    12,
		},
		{
			ID:       "bard-asi-12",
			ClassId:  1,
			Level:    12,
			Name:     "Ability Score Improvement",
			Priority: 13,
		},
		{
			ID:       "bard-asi-16",
			ClassId:  1,
			Level:    16,
			Name:     "Ability Score Improvement",
			Priority: 14,
		},
		{
			ID:          "bard-superior-inspiration",
			ClassId:     1,
			Level:       18,
			Name:        "Superior Inspiration",
			Description: "When you roll Initiative, you regain expended uses of Bardic Inspiration until you have 2 if you have fewer than that.",
			Priority:    15,
		},
		{
			ID:          "bard-epic-boon",
			ClassId:     1,
			Level:       19,
			Name:        "Epic Boon",
			Description: "You gain an Epic Boon feat or another feat of your choice for which you qualify.",
			Priority:    16,
		},
		{
			ID:          "bard-words-of-creation",
			ClassId:     1,
			Level:       20,
			Name:        "Words of Creation",
			Description: "You always have Power Word Heal and Power Word Kill prepared, and when you cast either spell, you can target a second creature if its within 10 ft. of the first target.",
			Priority:    17,
		},
		{
			ID:       "fighter-proficiencies",
			ClassId:  2,
			Level:    1,
			Name:     "Proficiencies",
			Priority: 1,
		},
		{
			ID:          "fighter-fighting-style",
			ClassId:     2,
			Level:       1,
			Name:        "Fighting Style",
			Description: "You adopt a fighting style speciality",
			Priority:    2,
		},
		{
			ID:          "fighter-second-wind",
			ClassId:     2,
			Level:       1,
			Name:        "Second Wind",
			Description: "Once per short rest, you can use a bonus action to regain 1d10 + your fighter level HP.",
			Priority:    3,
		},
		{
			ID:          "fighter-action-surge",
			ClassId:     2,
			Level:       2,
			Name:        "Action Surge",
			Description: "You can take one additional action on your turn. This can be used 1 ([17th] 2) times per short rest.",
			Priority:    4,
		},
		{
			ID:       "fighter-martial-archetype",
			ClassId:  2,
			Level:    3,
			Name:     "Martial Archetype",
			Priority: 5,
		},
		{
			ID:       "fighter-asi-4",
			ClassId:  2,
			Level:    4,
			Name:     "Ability Score Improvement",
			Priority: 6,
		},
		{
			ID:          "fighter-extra-attack-5",
			ClassId:     2,
			Level:       5,
			Name:        "Extra Attack",
			Description: "You can attack 2 ([11th] 3, [20th] 4) times whenever you take the Attack action on your turn.",
			Priority:    7,
		},
		{
			ID:       "fighter-asi-8",
			ClassId:  2,
			Level:    8,
			Name:     "Ability Score Improvement",
			Priority: 8,
		},
		{
			ID:          "fighter-indomitable",
			ClassId:     2,
			Level:       9,
			Name:        "Indomitable",
			Description: "You can reroll a saving throw that you fail - you must use the new roll. You can use this 1 ([13th] 2, [17th] 3) times per long rest.",
			Priority:    9,
		},
		{
			ID:          "fighter-extra-attack-11",
			ClassId:     2,
			Level:       11,
			Name:        "Extra Attack",
			Description: "You can attack 3 ([20th] 4) times whenever you take the Attack action on your turn.",
			Priority:    10,
		},
		{
			ID:       "fighter-asi-12",
			ClassId:  2,
			Level:    12,
			Name:     "Ability Score Improvement",
			Priority: 11,
		},
		{
			ID:       "fighter-asi-14",
			ClassId:  2,
			Level:    14,
			Name:     "Ability Score Improvement",
			Priority: 12,
		},
		{
			ID:       "fighter-asi-19",
			ClassId:  2,
			Level:    13,
			Name:     "Ability Score Improvement",
			Priority: 12,
		},
		{
			ID:          "fighter-extra-attack-20",
			ClassId:     2,
			Level:       20,
			Name:        "Extra Attack",
			Description: "You can attack 4 times whenever you take the Attack action on your turn.",
			Priority:    13,
		},
		{
			ID:       "blood-hunter-proficiencies",
			ClassId:  3,
			Level:    1,
			Name:     "Proficiencies",
			Priority: 1,
		},
		{
			ID:          "blood-hunter-hunters-bane",
			ClassId:     3,
			Level:       1,
			Name:        "Hunter's Bane",
			Description: "You have advantage on Wisdom (Survival) checks to track fey, fiends, or undead, and you have advantage on Intelligence ability checks to recall information about them.",
			Priority:    2,
		},
		{
			ID:      "blood-hunter-blood-maledict",
			ClassId: 3,
			Level:   1,
			Name:    "Blood Maledict",
			Description: `You can invoke a blood curse a number of times per short rest based on your level. Before it affects the target, you can choose to amplify the curse. An amplified curse gains an additional effect noted in the curse's description. Amplifying a curse causes you to take necrotic damage equal to one of your hemocraft die that cannot be reduced in any way.

Creatures that don't have blood in their bodies are immune to blood curses, unless the curse has been amplified.`,
			Priority: 3,
		},
		{
			ID:          "blood-hunter-blood-curses",
			ClassId:     3,
			Level:       1,
			Name:        "Blood Curses",
			Description: "Your chosen Blood Curses for use with the Blood Maledict feature.",
			Priority:    4,
		},
		{
			ID:          "blood-hunter-fighting-style",
			ClassId:     3,
			Level:       2,
			Name:        "Fighting Style",
			Description: "You adopt a fighting style specialty.",
			Priority:    5,
		},
		{
			ID:      "blood-hunter-crimson-rite",
			ClassId: 3,
			Level:   2,
			Name:    "Crimson Rite",
			Description: `As a bonus action, you can activate any rite you know on a weapon you're holding. A weapon can only hold one active rite at a time. When activated, you take necrotic damage equal to one of your hemocraft die which can't be reduced in any way.

While your rite is in effect, attacks made with this weapon are magical and you deal an additional damage equal to one of your hemocraft die of the type determined by the chosen rite. The rite’s effect lasts until you finish a short/long rest and other creatures cannot gain the benefit of your rite.`,
			Priority: 6,
		},
		{
			ID:       "blood-hunter-blood-hunter-order",
			ClassId:  3,
			Level:    3,
			Name:     "Blood Hunter Priority",
			Priority: 7,
		},
		{
			ID:       "blood-hunter-asi-4",
			ClassId:  3,
			Level:    4,
			Name:     "Ability Score Improvement",
			Priority: 8,
		},
		{
			ID:          "blood-hunter-extra-attack",
			ClassId:     3,
			Level:       5,
			Name:        "Extra Attack",
			Description: "Starting at 5th level, you can attack twice, instead of once, whenever you take the Attack action on your turn.",
			Priority:    9,
		},
		{
			ID:       "blood-hunter-brand-of-castigation",
			ClassId:  3,
			Level:    6,
			Name:     "Brand of Castigation",
			Priority: 10,
		},
		{
			ID:       "blood-hunter-asi-8",
			ClassId:  3,
			Level:    8,
			Name:     "Ability Score Improvement",
			Priority: 11,
		},
		{
			ID:          "blood-hunter-grim-psychometry",
			ClassId:     3,
			Level:       9,
			Name:        "Grim Psychometry",
			Description: "When making an Intelligence (History) check to recall information about the sinister or tragic history of an object you’re touching or your current location, you have advantage on the roll.",
			Priority:    12,
		},
		{
			ID:       "blood-hunter-dark-augmentation",
			ClassId:  3,
			Level:    10,
			Name:     "Dark Augmentation",
			Priority: 13,
		},
		{
			ID:       "blood-hunter-asi-12",
			ClassId:  3,
			Level:    12,
			Name:     "Ability Score Improvement",
			Priority: 14,
		},
		{
			ID:       "blood-hunter-brand-of-tethering",
			ClassId:  3,
			Level:    13,
			Name:     "Brand of Tethering",
			Priority: 15,
		},
		{
			ID:          "blood-hunter-hardened-soul",
			ClassId:     3,
			Level:       14,
			Name:        "Hardened Soul",
			Description: "You have advantage on saving throws against being charmed and frightened.",
			Priority:    16,
		},
		{
			ID:       "blood-hunter-asi-16",
			ClassId:  3,
			Level:    16,
			Name:     "Ability Score Improvement",
			Priority: 17,
		},
		{
			ID:       "blood-hunter-asi-19",
			ClassId:  3,
			Level:    19,
			Name:     "Ability Score Improvement",
			Priority: 18,
		},
		{
			ID:      "blood-hunter-sanguine-mastery",
			ClassId: 3,
			Level:   20,
			Name:    "Sanguine Mastery",
			Description: `Once per turn, whenever a blood hunter feature requires you to roll a hemocraft die, you can choose to reroll the die and use either roll.

In addition, whenever you score a critical hit with a weapon that has an active crimson rite, you regain one expended use of Blood Maledict.`,
			Priority: 19,
		},
	}

	for _, classFeature := range classFeatures {
		err := s.DB.Where("id = ?", classFeature.ID).FirstOrCreate(&classFeature).Error
		if err != nil {
			log.Printf("Error creating class feature with id %v in seeder: %v", classFeature.ID, err.Error())
		}
	}
}
