package seeders

import (
	m "dnd-api/db/models"
	"log"
)

func (s *Seeder) SetClassSpellSlots() {
	classSpellSlots := []*m.ClassSpellSlots{
		{
			ID:         1,
			ClassId:    2,
			ClassLevel: 1,
			SpellLevel: 1,
			SpellSlots: 2,
		},
		{
			ID:         2,
			ClassId:    2,
			ClassLevel: 2,
			SpellLevel: 1,
			SpellSlots: 3,
		},
		{
			ID:         3,
			ClassId:    2,
			ClassLevel: 3,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         4,
			ClassId:    2,
			ClassLevel: 3,
			SpellLevel: 2,
			SpellSlots: 1,
		},
		{
			ID:         5,
			ClassId:    2,
			ClassLevel: 4,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         6,
			ClassId:    2,
			ClassLevel: 4,
			SpellLevel: 2,
			SpellSlots: 2,
		},
		{
			ID:         7,
			ClassId:    2,
			ClassLevel: 5,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         8,
			ClassId:    2,
			ClassLevel: 5,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         9,
			ClassId:    2,
			ClassLevel: 5,
			SpellLevel: 3,
			SpellSlots: 2,
		},
		{
			ID:         10,
			ClassId:    2,
			ClassLevel: 6,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         11,
			ClassId:    2,
			ClassLevel: 6,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         12,
			ClassId:    2,
			ClassLevel: 6,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         13,
			ClassId:    2,
			ClassLevel: 7,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         14,
			ClassId:    2,
			ClassLevel: 7,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         15,
			ClassId:    2,
			ClassLevel: 7,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         16,
			ClassId:    2,
			ClassLevel: 7,
			SpellLevel: 4,
			SpellSlots: 1,
		},
		{
			ID:         17,
			ClassId:    2,
			ClassLevel: 8,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         18,
			ClassId:    2,
			ClassLevel: 8,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         19,
			ClassId:    2,
			ClassLevel: 8,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         20,
			ClassId:    2,
			ClassLevel: 8,
			SpellLevel: 4,
			SpellSlots: 2,
		},
		{
			ID:         21,
			ClassId:    2,
			ClassLevel: 9,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         22,
			ClassId:    2,
			ClassLevel: 9,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         23,
			ClassId:    2,
			ClassLevel: 9,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         24,
			ClassId:    2,
			ClassLevel: 9,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         25,
			ClassId:    2,
			ClassLevel: 9,
			SpellLevel: 5,
			SpellSlots: 1,
		},
		{
			ID:         26,
			ClassId:    2,
			ClassLevel: 10,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         27,
			ClassId:    2,
			ClassLevel: 10,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         28,
			ClassId:    2,
			ClassLevel: 10,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         29,
			ClassId:    2,
			ClassLevel: 10,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         30,
			ClassId:    2,
			ClassLevel: 10,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         31,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         32,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         33,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         34,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         35,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         36,
			ClassId:    2,
			ClassLevel: 11,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         37,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         38,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         39,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         40,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         41,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         42,
			ClassId:    2,
			ClassLevel: 12,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         43,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         44,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         45,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         46,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         47,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         48,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         49,
			ClassId:    2,
			ClassLevel: 13,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         50,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         51,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         52,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         53,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         54,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         55,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         56,
			ClassId:    2,
			ClassLevel: 14,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         57,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         58,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         59,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         60,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         61,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         62,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         63,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         64,
			ClassId:    2,
			ClassLevel: 15,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         65,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         66,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         67,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         68,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         69,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         70,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         71,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         72,
			ClassId:    2,
			ClassLevel: 16,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         73,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         74,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         75,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         76,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         77,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 5,
			SpellSlots: 2,
		},
		{
			ID:         78,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         79,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         80,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         81,
			ClassId:    2,
			ClassLevel: 17,
			SpellLevel: 9,
			SpellSlots: 1,
		},
		{
			ID:         82,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         83,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         84,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         85,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         86,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 5,
			SpellSlots: 3,
		},
		{
			ID:         87,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 6,
			SpellSlots: 1,
		},
		{
			ID:         88,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         89,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         90,
			ClassId:    2,
			ClassLevel: 18,
			SpellLevel: 9,
			SpellSlots: 1,
		},
		{
			ID:         91,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         92,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         93,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         94,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         95,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 5,
			SpellSlots: 3,
		},
		{
			ID:         96,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 6,
			SpellSlots: 2,
		},
		{
			ID:         97,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 7,
			SpellSlots: 1,
		},
		{
			ID:         98,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         99,
			ClassId:    2,
			ClassLevel: 19,
			SpellLevel: 9,
			SpellSlots: 1,
		},
		{
			ID:         100,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 1,
			SpellSlots: 4,
		},
		{
			ID:         101,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 2,
			SpellSlots: 3,
		},
		{
			ID:         102,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 3,
			SpellSlots: 3,
		},
		{
			ID:         103,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 4,
			SpellSlots: 3,
		},
		{
			ID:         104,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 5,
			SpellSlots: 3,
		},
		{
			ID:         105,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 6,
			SpellSlots: 2,
		},
		{
			ID:         106,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 7,
			SpellSlots: 2,
		},
		{
			ID:         107,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 8,
			SpellSlots: 1,
		},
		{
			ID:         108,
			ClassId:    2,
			ClassLevel: 20,
			SpellLevel: 9,
			SpellSlots: 1,
		},
	}

	for _, classSpellSlot := range classSpellSlots {
		err := s.DB.Where("id = ?", classSpellSlot.ID).FirstOrCreate(&classSpellSlot).Error
		if err != nil {
			log.Printf("Error create class spell slot with id %v in seeder: %v", classSpellSlot.ID, err.Error())
		}
	}
}
