package seeders

import (
	m "dnd-api/db/models"
	"log"
)

func (s *Seeder) SetClassSpellLevels() {
	classSpellLevels := []m.ClassSpellLevel{
		{
			ID:            1,
			ClassId:       1,
			ClassLevel:    1,
			SpellLevel:    1,
			NumberOfSlots: 2,
		},
		{
			ID:            2,
			ClassId:       1,
			ClassLevel:    2,
			SpellLevel:    1,
			NumberOfSlots: 3,
		},
		{
			ID:            3,
			ClassId:       1,
			ClassLevel:    3,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            4,
			ClassId:       1,
			ClassLevel:    3,
			SpellLevel:    2,
			NumberOfSlots: 2,
		},
		{
			ID:            5,
			ClassId:       1,
			ClassLevel:    4,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            6,
			ClassId:       1,
			ClassLevel:    4,
			SpellLevel:    2,
			NumberOfSlots: 2,
		},
		{
			ID:            7,
			ClassId:       1,
			ClassLevel:    5,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            7,
			ClassId:       1,
			ClassLevel:    5,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            8,
			ClassId:       1,
			ClassLevel:    5,
			SpellLevel:    3,
			NumberOfSlots: 2,
		},
		{
			ID:            9,
			ClassId:       1,
			ClassLevel:    6,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            10,
			ClassId:       1,
			ClassLevel:    6,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            11,
			ClassId:       1,
			ClassLevel:    6,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            12,
			ClassId:       1,
			ClassLevel:    7,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            13,
			ClassId:       1,
			ClassLevel:    7,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            14,
			ClassId:       1,
			ClassLevel:    7,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            15,
			ClassId:       1,
			ClassLevel:    7,
			SpellLevel:    4,
			NumberOfSlots: 1,
		},
		{
			ID:            16,
			ClassId:       1,
			ClassLevel:    8,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            17,
			ClassId:       1,
			ClassLevel:    8,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            18,
			ClassId:       1,
			ClassLevel:    8,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            19,
			ClassId:       1,
			ClassLevel:    8,
			SpellLevel:    4,
			NumberOfSlots: 2,
		},
		{
			ID:            20,
			ClassId:       1,
			ClassLevel:    9,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            21,
			ClassId:       1,
			ClassLevel:    9,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            22,
			ClassId:       1,
			ClassLevel:    9,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            23,
			ClassId:       1,
			ClassLevel:    9,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            23,
			ClassId:       1,
			ClassLevel:    9,
			SpellLevel:    5,
			NumberOfSlots: 1,
		},
		{
			ID:            24,
			ClassId:       1,
			ClassLevel:    10,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            25,
			ClassId:       1,
			ClassLevel:    10,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            26,
			ClassId:       1,
			ClassLevel:    10,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            27,
			ClassId:       1,
			ClassLevel:    10,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            28,
			ClassId:       1,
			ClassLevel:    10,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            28,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            29,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            30,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            31,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            32,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            33,
			ClassId:       1,
			ClassLevel:    11,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            34,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            35,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            36,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            37,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            38,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            39,
			ClassId:       1,
			ClassLevel:    12,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            40,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            41,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            42,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            43,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            44,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            45,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            46,
			ClassId:       1,
			ClassLevel:    13,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            47,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            48,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            49,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            50,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            51,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            52,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            53,
			ClassId:       1,
			ClassLevel:    14,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            54,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            55,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            56,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            57,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            58,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            59,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            60,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            61,
			ClassId:       1,
			ClassLevel:    15,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            62,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            63,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            64,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            65,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            66,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            67,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            68,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            69,
			ClassId:       1,
			ClassLevel:    16,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            70,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            71,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            72,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            73,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            74,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    5,
			NumberOfSlots: 2,
		},
		{
			ID:            75,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            76,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            77,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            78,
			ClassId:       1,
			ClassLevel:    17,
			SpellLevel:    9,
			NumberOfSlots: 1,
		},
		{
			ID:            79,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            80,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            81,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            82,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            83,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    5,
			NumberOfSlots: 3,
		},
		{
			ID:            84,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    6,
			NumberOfSlots: 1,
		},
		{
			ID:            85,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            86,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            87,
			ClassId:       1,
			ClassLevel:    18,
			SpellLevel:    9,
			NumberOfSlots: 1,
		},
		{
			ID:            88,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            89,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            90,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            91,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            92,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    5,
			NumberOfSlots: 3,
		},
		{
			ID:            93,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    6,
			NumberOfSlots: 2,
		},
		{
			ID:            94,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    7,
			NumberOfSlots: 1,
		},
		{
			ID:            95,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            96,
			ClassId:       1,
			ClassLevel:    19,
			SpellLevel:    9,
			NumberOfSlots: 1,
		},
		{
			ID:            97,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    1,
			NumberOfSlots: 4,
		},
		{
			ID:            98,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    2,
			NumberOfSlots: 3,
		},
		{
			ID:            99,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    3,
			NumberOfSlots: 3,
		},
		{
			ID:            100,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    4,
			NumberOfSlots: 3,
		},
		{
			ID:            101,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    5,
			NumberOfSlots: 3,
		},
		{
			ID:            102,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    6,
			NumberOfSlots: 2,
		},
		{
			ID:            103,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    7,
			NumberOfSlots: 2,
		},
		{
			ID:            104,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    8,
			NumberOfSlots: 1,
		},
		{
			ID:            105,
			ClassId:       1,
			ClassLevel:    20,
			SpellLevel:    9,
			NumberOfSlots: 1,
		},
	}

	for _, classSpellLevel := range classSpellLevels {
		err := s.DB.Where("id = ?", classSpellLevel.ID).FirstOrCreate(&classSpellLevel).Error
		if err != nil {
			log.Printf("Error creating class spell level with id %v in seeder: %v", classSpellLevel.ID, err.Error())
		}
	}
}
