package seeders

import (
	m "dnd-api/db/models"
	"dnd-api/pkg/utils"
	"log"
)

func (s *Seeder) SetItems() {
	items := []m.Item{
		{
			ID:         1,
			Name:       "Dagger",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityCommon,
			Origin:     "Weapon",
			Weight:     1,
			Cost:       2,
			Equippable: true,
			Notes:      "Simple, Finesse, Light, Thrown, Nick, Range (20/60)",
		},
		{
			ID:         2,
			Name:       "Rapier, +1",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityUncommon,
			Origin:     "Weapon",
			Weight:     2,
			Cost:       200,
			Equippable: true,
			Notes:      "Martial, Finesse, Vex",
		},
		{
			ID:         3,
			Name:       "Leather Armour",
			Type:       m.ItemTypeArmour,
			Rarity:     m.RarityCommon,
			Origin:     "Light Armour",
			Weight:     10,
			Cost:       10,
			Equippable: true,
			Notes:      "AC 11",
		},
		{
			ID:     4,
			Name:   "Lute",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Gear",
			Weight: 2,
			Cost:   35,
			Notes:  "Instrument",
		},
		{
			ID:     5,
			Name:   "Bedroll",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 7,
			Cost:   1,
			Notes:  "Utility",
		},
		{
			ID:     6,
			Name:   "Bell",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 0.2,
			Cost:   1,
			Notes:  "Communication, Utility",
		},
		{
			ID:     7,
			Name:   "Bullseye Lantern",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 2,
			Cost:   10,
			Notes:  "Utility, Exploration",
		},
		{
			ID:     8,
			Name:   "Costume",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 4,
			Cost:   5,
			Notes:  "Social, Deception, Outerwear",
		},
		{
			ID:     9,
			Name:   "Mirror",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 0.5,
			Cost:   5,
			Notes:  "Social, Utility",
		},
		{
			ID:     10,
			Name:   "Oil",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 1,
			Cost:   0.1,
			Notes:  "Damage, Utility, Combat",
		},
		{
			ID:     11,
			Name:   "Rations",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 2,
			Cost:   0.5,
			Notes:  "Social, Utility, Consumable",
		},
		{
			ID:     12,
			Name:   "Tinderbox",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 1,
			Cost:   0.5,
			Notes:  "Utility, Exploration",
		},
		{
			ID:     13,
			Name:   "Waterskin",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 5,
			Cost:   0.2,
			Notes:  "Container",
		},
		{
			ID:                  14,
			Name:                "Rock Watch",
			Type:                m.ItemTypeItem,
			Rarity:              m.RarityRare,
			Origin:              "Wondrous Item",
			Weight:              1,
			Cost:                50,
			Notes:               "1 Charge, Jewelry",
			Equippable:          true,
			InitiativeAdvantage: true,
		},
		{
			ID:                    15,
			Name:                  "Cloak of Protection",
			Type:                  m.ItemTypeItem,
			Rarity:                m.RarityUncommon,
			Origin:                "Wondrous Item",
			Weight:                2,
			Cost:                  50,
			Notes:                 "Warding, Outerwear",
			Equippable:            true,
			StrengthSaveBonus:     1,
			DexteritySaveBonus:    1,
			ConstitutionSaveBonus: 1,
			IntelligenceSaveBonus: 1,
			WisdomSaveBonus:       1,
			CharismaSaveBonus:     1,
			ArmourClassBonus:      1,
			SavingThrowBonusType:  utils.StrPointer(m.SavingThrowBonusTypeAdd),
			SavingThrowBonusText:  "1 on saves",
		},
		{
			ID:         16,
			Name:       "Chain Mail",
			Type:       m.ItemTypeArmour,
			Rarity:     m.RarityCommon,
			Origin:     "Heavy Armour",
			Weight:     55,
			Cost:       75,
			Notes:      "AC 16, STR 13, Stealth Disadv.",
			Equippable: true,
		},
		{
			ID:     17,
			Name:   "Clothes, Common",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 3,
			Cost:   0.5,
			Notes:  "Social, Outerwear",
		},
		{
			ID:         18,
			Name:       "Greataxe",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityCommon,
			Origin:     "Weapon",
			Weight:     7,
			Cost:       30,
			Equippable: true,
			Notes:      "Martial, Heavy, Two-Handed, Cleave",
		},
		{
			ID:         19,
			Name:       "Handaxe",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityCommon,
			Origin:     "Weapon",
			Weight:     2,
			Cost:       5,
			Equippable: true,
			Notes:      "Simple, Light, Thrown, Vex, Range (20/60)",
		},
		{
			ID:     20,
			Name:   "Log Trinket",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Jewelry",
			Weight: 0.2,
			Cost:   1,
			Notes:  "Social, Jewelry",
		},
		{
			ID:         21,
			Name:       "Morningstar",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityCommon,
			Origin:     "Weapon",
			Weight:     4,
			Cost:       15,
			Equippable: true,
			Notes:      "Martial, Sap",
		},
		{
			ID:     22,
			Name:   "Bear Meat",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 5,
			Cost:   0.5,
			Notes:  "Consumable",
		},
		{
			ID:     23,
			Name:   "Crowbar",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 5,
			Cost:   2,
			Notes:  "Utility, Exploration",
		},
		{
			ID:     24,
			Name:   "Hammer",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 3,
			Cost:   1,
			Notes:  "Utility",
		},
		{
			ID:     25,
			Name:   "Monk's Skull",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Holy Symbol",
			Weight: 2,
			Cost:   0.2,
			Notes:  "Taken from Savras' Church in Myrefall",
		},
		{
			ID:     26,
			Name:   "Piton",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 0.25,
			Cost:   0.05,
			Notes:  "Utility, Exploration",
		},
		{
			ID:     27,
			Name:   "Token of Lliira",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Holy Symbol",
			Weight: 0.2,
			Cost:   1,
			Notes:  "Social, Jewelry",
		},
		{
			ID:     28,
			Name:   "Torch",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 1,
			Cost:   0.01,
			Notes:  "Damage, Utility, Exploration, Combat",
		},
		{
			ID:     29,
			Name:   "Rope (50 ft.)",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 10,
			Cost:   1,
			Notes:  "Utility, Exploration",
		},
		{
			ID:         30,
			Name:       "Dagger of Returning",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityUncommon,
			Origin:     "Weapon",
			Weight:     1,
			Cost:       200,
			Equippable: true,
			Notes:      "Simple, Finesse, Light, Thrown, Nick, Range (20/60)",
		},
		{
			ID:     31,
			Name:   "Alchemist's Supplies",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Gear - Tool",
			Weight: 8,
			Cost:   50,
			Notes:  "Utility",
		},
		{
			ID:     32,
			Name:   "Crossbow Bolts",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Gear - Ammunition",
			Weight: 0.075,
			Cost:   0.05,
			Notes:  "Damage, Combat",
		},
		{
			ID:         33,
			Name:       "Crossbow, Light",
			Type:       m.ItemTypeWeapon,
			Rarity:     m.RarityCommon,
			Origin:     "Weapon",
			Weight:     5,
			Cost:       2,
			Notes:      "Simple, Ammunition, Loading, Two-Handed, Slow, Range (80/320)",
			Equippable: true,
		},
		{
			ID:     34,
			Name:   "Potion of Healing",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Gear",
			Weight: 0.5,
			Cost:   50,
			Notes:  "Healing, Combat, Consumable",
		},
		{
			ID:               35,
			Name:             "Shield",
			Type:             m.ItemTypeItem,
			Rarity:           m.RarityCommon,
			Origin:           "Shield",
			Weight:           6,
			Cost:             10,
			Equippable:       true,
			Notes:            "+2 AC",
			ArmourClassBonus: 2,
		},
		{
			ID:     36,
			Name:   "Spider Venom",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Gear - Poison",
			Weight: 0.5,
			Cost:   100,
			Notes:  "Damage, Utility, Combat, Consumable",
		},
		{
			ID:         37,
			Name:       "Studded Leather",
			Type:       m.ItemTypeArmour,
			Rarity:     m.RarityCommon,
			Origin:     "Light Armour",
			Weight:     13,
			Cost:       45,
			Equippable: true,
			Notes:      "AC 12",
		},
		{
			ID:     38,
			Name:   "Mess Kit",
			Type:   m.ItemTypeItem,
			Rarity: m.RarityCommon,
			Origin: "Adventuring Gear",
			Weight: 1,
			Cost:   0.2,
			Notes:  "Social, Utility",
		},
	}

	for _, item := range items {
		err := s.DB.Where("id = ?", item.ID).FirstOrCreate(&item).Error
		if err != nil {
			log.Printf("Error creating item with id %v in seeder: %v", item.ID, err.Error())
		}
	}
}
