package seeders

import (
	m "dnd-api/db/models"
	"dnd-api/pkg/utils"
	"log"
)

func (s *Seeder) SetSpells() {
	spells := []*m.Spell{
		{
			ID:          1,
			Name:        "Mage Hand",
			School:      m.MagicSchoolConjuration,
			CastingTime: "1A",
			Distance:    "30 ft.",
			Effect:      "Utility",
			Notes:       "D: 1m, V/S",
		},
		{
			ID:          2,
			Name:        "Prestidigitation",
			School:      m.MagicSchoolTransmutation,
			CastingTime: "1A",
			Distance:    "10 ft.",
			Effect:      "Utility",
			Notes:       "D: 1h, V/S",
		},
		{
			ID:          3,
			Name:        "Starry Wisp",
			School:      m.MagicSchoolEvocation,
			CastingTime: "1A",
			Distance:    "60 ft.",
			IsAttack:    true,
			Damage:      utils.StrPointer("2d8"),
			DamageType:  utils.StrPointer(m.DamageTypeRadiant),
			Effect:      "Damage",
			Notes:       "V/S",
		},
		{
			ID:          4,
			Name:        "Charm Person",
			School:      m.MagicSchoolEnchantment,
			Level:       1,
			CastingTime: "1A",
			Distance:    "30 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("WIS"),
			Effect:      "Charmed",
			Notes:       "D: 1h, V/S",
			CanUpcast:   true,
		},
		{
			ID:          5,
			Name:        "Comprehend Languages",
			School:      m.MagicSchoolDivination,
			Level:       1,
			CastingTime: "1A",
			Distance:    "Self",
			Effect:      "Social",
			Notes:       "D: 1h, V/S/M",
		},
		{
			ID:          6,
			Name:        "Earth Tremor",
			School:      "Evocation",
			Level:       1,
			CastingTime: "1A",
			Distance:    "10 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("DEX"),
			Damage:      utils.StrPointer("1d6"),
			DamageType:  utils.StrPointer(m.DamageTypeBludgeoning),
			Effect:      "Damage",
			Notes:       "V/S",
			CanUpcast:   true,
		},
		{
			ID:          7,
			Name:        "Sleep",
			School:      m.MagicSchoolEnchantment,
			Level:       1,
			CastingTime: "1A",
			Distance:    "60 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("WIS"),
			Effect:      "Incapacitated",
			Notes:       "D: 1m, 5ft. Sphere, V/S/M",
		},
		{
			ID:          8,
			Name:        "Unseen Servant",
			School:      m.MagicSchoolConjuration,
			Level:       1,
			CastingTime: "1A",
			Distance:    "60 ft.",
			Effect:      "Control",
			Notes:       "D: 1h, V/S/M",
		},
		{
			ID:          9,
			Name:        "Enlarge/Reduce",
			School:      m.MagicSchoolTransmutation,
			Level:       2,
			CastingTime: "1A",
			Distance:    "30 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("CON"),
			Effect:      "Buff",
			Notes:       "D: 1m, V/S/M",
		},
		{
			ID:          10,
			Name:        "Heat Metal",
			School:      m.MagicSchoolTransmutation,
			Level:       2,
			CastingTime: "1A",
			Distance:    "60 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("CON"),
			Effect:      "Damage",
			Damage:      utils.StrPointer("2d8"),
			DamageType:  utils.StrPointer(m.DamageTypeFire),
			Notes:       "D: 1m, V/S/M",
			CanUpcast:   true,
		},
		{
			ID:          11,
			Name:        "Pass Without Trace",
			School:      m.MagicSchoolAbjuration,
			Level:       2,
			CastingTime: "1A",
			Distance:    "Self",
			Effect:      "Buff",
			Notes:       "1/LR, D: 1h, V/S/M",
		},
		{
			ID:          12,
			Name:        "Phantasmal Force",
			School:      m.MagicSchoolIllusion,
			Level:       2,
			CastingTime: "1A",
			Distance:    "60 ft.",
			IsSave:      true,
			Effect:      "Damage",
			SaveAbility: utils.StrPointer("INT"),
			Damage:      utils.StrPointer("2d8"),
			DamageType:  utils.StrPointer(m.DamageTypePsychic),
			Notes:       "D: 1m, 10ft. Cube, V/S/M",
		},
		{
			ID:          13,
			Name:        "Dispel Magic",
			School:      m.MagicSchoolAbjuration,
			Level:       3,
			CastingTime: "1A",
			Distance:    "120 ft.",
			Effect:      "Control",
			Notes:       "V/S",
			CanUpcast:   true,
		},
		{
			ID:          14,
			Name:        "Slow",
			School:      m.MagicSchoolTransmutation,
			Level:       3,
			CastingTime: "1A",
			Distance:    "120 ft.",
			IsSave:      true,
			SaveAbility: utils.StrPointer("WIS"),
			Effect:      "Control",
			Notes:       "D: 1m, 40ft. Cube, V/S/M",
		},
		{
			ID:          15,
			Name:        "Booming Blade",
			School:      m.MagicSchoolEvocation,
			Level:       0,
			CastingTime: "1A",
			Distance:    "Self",
			Effect:      "Damage",
			Damage:      utils.StrPointer("1d8"),
			DamageType:  utils.StrPointer(m.DamageTypeThunder),
			Notes:       "D: 1Rnd, 5ft. Sphere, S/M",
		},
		{
			ID:          16,
			Name:        "Fog Cloud",
			School:      m.MagicSchoolConjuration,
			Level:       1,
			CastingTime: "1A",
			Distance:    "120 ft.",
			Effect:      "Control",
			Notes:       "D: 1h, 20ft. Sphere, V/S",
		},
		{
			ID:          17,
			Name:        "Misty Step",
			School:      m.MagicSchoolConjuration,
			Level:       2,
			CastingTime: "1BA",
			Distance:    "Self",
			Effect:      "Teleportation",
			Notes:       "V",
		},
		{
			ID:          18,
			Name:        "Silvery Barbs",
			School:      m.MagicSchoolEnchantment,
			Level:       1,
			CastingTime: "1R",
			Distance:    "60 ft.",
			Effect:      "Control",
			Notes:       "V",
		},
	}

	for _, spell := range spells {
		err := s.DB.Where("id = ?", spell.ID).FirstOrCreate(&spell).Error
		if err != nil {
			log.Printf("Error creating spell with id %v in seeder: %v", spell.ID, err.Error())
		}
	}
}
